spring.application.name=account

# Run on a different port than your main API (8080) and Eureka (8761)
server.port=8081

# Tell this service where the Eureka server is located
eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka/